Repository woowa-techcamp-2021/baemin-11, pull requests merged in 2021-07, with the labels that each got.

#40 Feature/directory init
  .gitignore
  app.js
  bin/www
  lib/Database.js
  middlewares/auth.js
  middlewares/index.js
  models/user.js
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/user.js
  services/user.js
  views/error.pug
  views/index.pug
Labels: Backend

#41 login layout 개발
  app.js
  public/css/components/textButton.css
  public/css/global.css
  public/css/login.css
  public/css/style.css
  public/resource/battery.png
  public/resource/reception.png
  public/resource/wifi.png
  routes/login.js
  views/components/LoginForm.pug
  views/components/SocialLoginContainer.pug
  views/components/SubHeader.pug
  views/components/TextButton.pug
  views/screens/Login.pug
Labels: Frontend

#42 Feature/agreement layout
  public/css/components/button.css
  public/css/components/checkboxitem.css
  public/css/components/radioitem.css
  public/css/components/statusbar.css
  public/css/components/subheader.css
  public/css/global.css
  public/css/pages/agreement.css
  public/css/variables.css
  public/images/arrow-back.svg
  public/images/battery.svg
  public/images/chevron-forward.svg
  public/images/close.svg
  public/images/reception.svg
  public/images/wifi.svg
  public/js/agreement.js
  routes/index.js
  views/Layout.pug
  views/components/Button.pug
  views/components/CheckboxItem.pug
  views/components/RadioItem.pug
  views/components/StatusBar.pug
  views/components/SubHeader.pug
  views/index.pug
  views/pages/Agreement.pug
Labels: Frontend

#43 express에 폴더 구조 추가
  app.js
  lib/Database.js
  middlewares/auth.js
  middlewares/index.js
  models/user.js
  routes/user.js
  services/user.js
Labels: Backend

#44 Login Screen Mock-Up 개발했습니다.
  public/css/components/loginForm.css
  public/css/components/primebutton.css
  public/css/components/socialLoginButton.css
  public/css/components/textButton.css
  public/css/global.css
  public/css/login.css
  public/css/screens/agreement.css
  public/css/screens/login.css
  public/css/variables.css
  public/resource/apple-logo.png
  public/resource/arrow-back.svg
  public/resource/battery.svg
  public/resource/chevron-forward.svg
  public/resource/close.svg
  public/resource/facebook-logo.png
  public/resource/naver-logo.png
  public/resource/reception.svg
  public/resource/wifi.svg
  views/Layout.pug
  views/components/LoginForm.pug
  views/components/PrimeButton.pug
  views/components/SocialLoginButton.pug
  views/components/SocialLoginContainer.pug
  views/components/StatusBar.pug
  views/components/TextButton.pug
  views/screens/Agreement.pug
  views/screens/Login.pug
Labels: Frontend

#47 container 클래스 버그 수정
  public/css/global.css
  views/screens/Main.pug
Labels: bug

#49 DB Insert 기능 구현했습니다.
  .gitignore
  lib/insertQuery.js
  lib/util.js
Labels: Backend

#50 Webpack, livereload를 추가해봤습니다.
  app.js
  assets/screens/agreement.js
  assets/utils/$.js
  package-lock.json
  package.json
  public/js/agreement.js
  views/Layout.pug
  webpack.js
Labels: Backend

#48 InputPhone / Email 2개 스크린 목업 완성했습니다.
  app.js
  public/css/components/checkInput.css
  public/css/components/subButton.css
  public/css/global.css
  public/css/screens/inputEmail.css
  public/css/screens/inputPhone.css
  public/css/variables.css
  public/resource/cancel.png
  public/resource/grayCheck.png
  public/resource/mintCheck.png
  routes/inputEmail.js
  routes/inputPhone.js
  views/components/CheckInput.pug
  views/components/SubButton.pug
  views/screens/InputEmail.pug
  views/screens/InputPhone.pug
Labels: Frontend

#51 checkbox, radiobox에 사용할 이미지 추가 및 라우터 연결
  public/css/components/checkboxitem.css
  public/css/components/radioitem.css
  public/css/screens/agreement.css
  public/resource/14agedown_F.png
  public/resource/14agedown_T.png
  public/resource/14ageup_F.png
  public/resource/14ageup_T.png
  public/resource/checkbox_F.png
  public/resource/checkbox_T.png
  views/components/CheckboxItem.pug
  views/components/RadioItem.pug
  views/screens/Agreement.pug
Labels: Frontend

#54 github actions 자동배포 추가
  .github/workflows/dev-cd.yml
  .github/workflows/main-cd.yml
  routes/index.js
Labels: Additional implement

#57 db 함수들 모두 구현했습니다.
  lib/Database.js
  lib/deleteQuery.js
  lib/ex.js
  lib/insertQuery.js
  lib/selectQuery.js
  lib/util.js
Labels: Backend

#56 Main Screen Script 연결 완료했습니다.
  public/css/components/defaultcontainer.css
  public/css/components/mainheader.css
  public/css/screens/main.css
  public/css/variables.css
  public/resource/chevron-forward.svg
  public/resource/coupon.png
  public/resource/order.png
  public/resource/plant.png
  public/resource/point.png
  public/resource/present.png
  public/resource/profile.png
  public/resource/review.png
  public/resource/zzim.png
  views/components/DefaultContainer.pug
  views/screens/Main.pug
Labels: Frontend

#59 Login screen 기능 구현
  assets/screens/login.js
  assets/utils/$.js
  assets/utils/throttle.js
  assets/utils/validInput.js
  assets/utils/validator.js
  public/css/components/input.css
  public/css/global.css
  public/css/variables.css
  public/js/login.js
  views/components/Button.pug
  views/components/Input.pug
  views/components/LoginForm.pug
  views/screens/Login.pug
Labels: Frontend

#60 본인인증화면(휴대폰) fe 기능 구현
  assets/screens/inputPhone.js
  assets/utils/$.js
  assets/utils/inputUtils.js
  assets/utils/validator.js
  public/js/inputPhone.js
  public/js/login.js
  views/components/SubButton.pug
  views/screens/InputPhone.pug
Labels: Frontend

#61 약관 동의 페이지 스크립트 완성.
  assets/screens/agreement.js
  public/css/components/button.css
  public/css/components/checkboxitem.css
  public/css/components/subheader.css
  public/css/screens/agreement.css
  public/js/agreement.js
  views/components/CheckboxItem.pug
  views/components/RadioItem.pug
  views/components/SubHeader.pug
  views/screens/Agreement.pug
Labels: Frontend

#65 api 개발 및 session 과 cookie 사용하여 개발 완료했습니다.
  app.js
  lib/defaultLocation.js
  lib/deleteQuery.js
  lib/insertQuery.js
  lib/selectQuery.js
  lib/util.js
  middlewares/auth.js
  middlewares/session.js
  package-lock.json
  package.json
  routes/agreement.js
  routes/api.js
  routes/index.js
  routes/inputEmail.js
  routes/inputPhone.js
  routes/login.js
  views/components/Input.pug
  views/components/LoginForm.pug
  views/screens/Login.pug
Labels: Backend

#66 UI 오류 및 버튼 에러 해결
  assets/screens/agreement.js
  public/css/components/radioitem.css
  public/css/components/socialLoginButton.css
  public/js/agreement.js
Labels: Frontend, bug

#69 본인인증화면(이메일) js 기능 구현
  assets/screens/inputEmail.js
  assets/screens/inputPhone.js
  assets/screens/login.js
  assets/utils/inputUtils.js
  assets/utils/tmpl.js
  assets/utils/validInput.js
  assets/utils/validator.js
  public/css/components/input.css
  public/css/components/subButton.css
  public/css/components/subheader.css
  public/css/screens/inputEmail.css
  public/js/inputEmail.js
  public/js/inputPhone.js
  public/js/login.js
  views/components/Input.pug
  views/components/SubButton.pug
  views/components/SubHeader.pug
  views/screens/InputEmail.pug
  views/screens/InputPhone.pug
Labels: Frontend

#71 백엔드 API를 프론트에 연결, 버그 픽스
  assets/components/subheader.js
  assets/screens/inputEmail.js
  assets/screens/inputPhone.js
  assets/screens/login.js
  middlewares/session.js
  public/css/components/subButton.css
  public/js/inputEmail.js
  public/js/inputPhone.js
  public/js/login.js
  routes/api.js
  views/components/Input.pug
  views/components/LoginForm.pug
  views/screens/Login.pug
Labels: Frontend

#70 Number Pad 만들었습니다.
  assets/screens/dial.js
  assets/screens/inputPhone.js
  assets/screens/login.js
  public/css/components/englishPad.css
  public/css/components/numberPad.css
  public/js/dial.js
  public/js/inputPhone.js
  public/js/login.js
  routes/index.js
  views/components/EnglishPad.pug
  views/components/NumberPad.pug
  views/screens/InputEmail.pug
  views/screens/InputPhone.pug
  views/screens/Login.pug
  views/screens/Pad.pug
Labels: Frontend

#72 배포 전 버그 수정
  assets/screens/inputEmail.js
  assets/screens/login.js
  public/js/inputEmail.js
  public/js/inputPhone.js
  public/js/login.js
  routes/api.js
  views/screens/InputEmail.pug
  views/screens/InputPhone.pug
Labels: bug
